# Generated by Django 5.0.3 on 2024-03-11 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wilsonbackend.mediafile')),
                ('duration', models.DurationField()),
                ('bitrate', models.IntegerField()),
            ],
            bases=('wilsonbackend.mediafile',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wilsonbackend.mediafile')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            bases=('wilsonbackend.mediafile',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wilsonbackend.mediafile')),
                ('duration', models.DurationField()),
                ('thumbnail', models.URLField()),
            ],
            bases=('wilsonbackend.mediafile',),
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_files', models.ManyToManyField(related_name='media_items', to='wilsonbackend.mediafile')),
            ],
        ),
    ]
