# Generated by Django 5.0.3 on 2024-03-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilsonbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='format',
            field=models.CharField(default='mp3', max_length=10),
        ),
        migrations.AddField(
            model_name='image',
            name='format',
            field=models.CharField(default='jpeg', max_length=10),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='creator',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='format',
            field=models.CharField(default='mp4', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.CharField(default='1080p', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitles_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
